export const GET_PHRASE = "GET_PHRASE";
export const GET_PHRASES_SUCCESS = "GET_PHRASES_SUCCESS";
export const GET_PHRASE_SEARCH = "GET_PHRASE_SEARCH";
export const GET_PHRASES_SEARCH_SUCCESS = "GET_PHRASES_SEARCH_SUCCESS";
export const ADD_PHRASE = "ADD_PHRASE";
export const ADD_PHRASES_SUCCESS = "ADD_PHRASES_SUCCESS";
export const DELETE_PHRASE = "ADD_PHRASE";
export const DELETE_PHRASES_SUCCESS = "ADD_PHRASES_SUCCESS";
export const DELETE_PHRASES_FAILURE = "DELETE_PHRASES_FAILURE";
// Auth
export const userConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
};
