export const phraseConstants = {
  GET_PHRASE: "GET_PHRASE",
  GET_PHRASES_SUCCESS: "GET_PHRASES_SUCCESS",
  GET_PHRASE_SEARCH: "GET_PHRASE_SEARCH",
  GET_PHRASES_SEARCH_SUCCESS: "GET_PHRASES_SEARCH_SUCCESS",
  ADD_PHRASE: "ADD_PHRASE",
  ADD_PHRASES_SUCCESS: "ADD_PHRASES_SUCCESS",
  ADD_PHRASE_FAILURE: "ADD_PHRASE_FAILURE",
  DELETE_PHRASE: "ADD_PHRASE",
  DELETE_PHRASES_SUCCESS: "ADD_PHRASES_SUCCESS",
  DELETE_PHRASES_FAILURE: "DELETE_PHRASES_FAILURE",
};
// Auth
export const userConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
};
